using BolunPhone.Shell.Models;

namespace BolunPhone.Shell.Services;

public static class DemoPhoneCatalog
{
    public static IReadOnlyList<AppModel> Apps { get; } = new List<AppModel>
    {
        new("phone", "Phone", "Communication", "☎", ConsoleColor.Blue),
        new("contacts", "Contacts", "Communication", "◎", ConsoleColor.DarkCyan),
        new("messages", "Messages", "Communication", "💬", ConsoleColor.Green),
        new("mail", "Email", "Communication", "✉", ConsoleColor.Blue),
        new("video-calls", "Video Calls", "Communication", "◉", ConsoleColor.Magenta),
        new("call-log", "Call Log", "Communication", "☷", ConsoleColor.Blue),
        new("browser", "Browser", "Internet", "🌐", ConsoleColor.Blue),
        new("youtube", "YouTube", "Internet", "▶", ConsoleColor.Red),
        new("dima30-store", "Dima30 Store", "Internet", "▣", ConsoleColor.DarkGreen),
        new("downloads", "Downloads", "Internet", "⇩", ConsoleColor.DarkCyan),
        new("vpn", "VPN", "Internet", "🔒", ConsoleColor.DarkGray),
        new("camera", "Camera", "Multimedia", "📷", ConsoleColor.DarkBlue),
        new("gallery", "Gallery", "Multimedia", "▧", ConsoleColor.DarkBlue),
        new("video", "Video", "Multimedia", "▶", ConsoleColor.DarkBlue),
        new("music", "Music", "Multimedia", "♪", ConsoleColor.DarkBlue),
        new("voice-recorder", "Voice Recorder", "Multimedia", "🎙", ConsoleColor.DarkGray),
        new("fm-radio", "FM Radio", "Multimedia", "◌", ConsoleColor.DarkGreen),
        new("notes", "Notes", "Office", "✎", ConsoleColor.Yellow),
        new("calendar", "Calendar", "Office", "8", ConsoleColor.DarkCyan),
        new("calculator", "Calculator", "Office", "±", ConsoleColor.Gray),
        new("clock", "Clock", "Office", "◷", ConsoleColor.DarkGray),
        new("alarm", "Alarm", "Office", "⏰", ConsoleColor.DarkGray),
        new("timer", "Timer", "Office", "⏱", ConsoleColor.DarkGray),
        new("stopwatch", "Stopwatch", "Office", "⏱", ConsoleColor.DarkGray),
        new("documents", "Documents", "Office", "▤", ConsoleColor.Gray),
        new("pdf-reader", "PDF Reader", "Office", "PDF", ConsoleColor.Red),
        new("file-manager", "File Manager", "Files", "📁", ConsoleColor.DarkMagenta),
        new("archiver", "Archiver", "Files", "ZIP", ConsoleColor.DarkMagenta),
        new("recycle-bin", "Recycle Bin", "Files", "♻", ConsoleColor.Gray),
        new("settings", "Settings", "System", "⚙", ConsoleColor.DarkGray),
        new("system-update", "System Update", "System", "⇧", ConsoleColor.Blue),
        new("security", "Security", "System", "🛡", ConsoleColor.DarkGreen),
        new("b-id", "B-ID", "System", "ID", ConsoleColor.Blue),
        new("bolun-account", "Bolun Account", "System", "👤", ConsoleColor.Blue),
        new("backup", "Backup", "System", "☁", ConsoleColor.Blue),
        new("restore", "Restore", "System", "↺", ConsoleColor.Blue),
        new("app-permissions", "App Permissions", "System", "✓", ConsoleColor.DarkGreen),
        new("storage", "Storage", "System", "▣", ConsoleColor.Gray),
        new("battery", "Battery", "System", "▰", ConsoleColor.DarkGreen),
        new("memory", "Memory", "System", "RAM", ConsoleColor.Gray),
        new("network", "Network", "System", "⇄", ConsoleColor.Blue),
        new("bluetooth", "Bluetooth", "System", "BT", ConsoleColor.Blue),
        new("wifi", "Wi-Fi", "System", "Wi", ConsoleColor.Blue),
        new("about", "About Device", "System", "i", ConsoleColor.Gray),
        new("maps", "Maps", "Maps and Navigation", "⌖", ConsoleColor.DarkCyan),
        new("navigator", "Navigator", "Maps and Navigation", "➤", ConsoleColor.DarkCyan),
        new("compass", "Compass", "Maps and Navigation", "◇", ConsoleColor.DarkCyan),
        new("weather", "Weather", "Maps and Navigation", "☀", ConsoleColor.Blue),
        new("bolun-ai", "Bolun AI", "Artificial Intelligence", "AI", ConsoleColor.Magenta),
        new("ai-camera", "AI Camera", "Artificial Intelligence", "◉", ConsoleColor.Magenta),
        new("ai-translator", "AI Translator", "Artificial Intelligence", "TR", ConsoleColor.Magenta),
        new("ai-ocr", "AI OCR", "Artificial Intelligence", "OCR", ConsoleColor.Magenta),
        new("ai-search", "AI Search", "Artificial Intelligence", "⌕", ConsoleColor.Magenta),
        new("ai-photo-editor", "AI Photo Editor", "Artificial Intelligence", "✦", ConsoleColor.Magenta),
        new("bolun-share", "Bolun Share", "Data Transfer", "⇄", ConsoleColor.Cyan),
        new("bolun-link", "Bolun Link", "Data Transfer", "∞", ConsoleColor.Cyan),
        new("bolun-cast", "Bolun Cast", "Data Transfer", "▭", ConsoleColor.Cyan),
        new("passwords", "Passwords", "Security", "🔑", ConsoleColor.DarkGreen),
        new("certificates", "Certificates", "Security", "CERT", ConsoleColor.DarkGreen),
        new("app-check", "App Check", "Security", "✓", ConsoleColor.DarkGreen),
        new("bolun-defender", "Bolun Defender", "Security", "🛡", ConsoleColor.DarkGreen),
        new("keyboard", "Keyboard", "Extras", "KBD", ConsoleColor.Gray),
        new("wallpapers", "Wallpapers", "Extras", "▧", ConsoleColor.DarkBlue),
        new("themes", "Themes", "Extras", "◫", ConsoleColor.DarkBlue),
        new("emoji", "Emoji", "Extras", "☺", ConsoleColor.Yellow),
        new("qr-scanner", "QR Scanner", "Extras", "QR", ConsoleColor.DarkGreen),
        new("document-scanner", "Document Scanner", "Extras", "SCAN", ConsoleColor.DarkGreen),
        new("notification-center", "Notification Center", "Extras", "🔔", ConsoleColor.Blue),
        new("control-center", "Control Center", "Extras", "☷", ConsoleColor.Blue),
        new("voice-assistant", "Voice Assistant", "Extras", "VOICE", ConsoleColor.Magenta),
        new("search", "Search", "Extras", "⌕", ConsoleColor.Blue),
        new("widgets", "Widgets", "Extras", "▦", ConsoleColor.Cyan),
        new("live-tiles", "Live Tiles", "Extras", "▣", ConsoleColor.Cyan),
        new("emergency", "Emergency Help", "Extras", "SOS", ConsoleColor.Red),
        new("feedback", "Feedback", "Extras", "?", ConsoleColor.Blue),
        new("licenses", "Licenses", "Extras", "§", ConsoleColor.Gray),
        new("user-guide", "User Guide", "Extras", "HELP", ConsoleColor.Gray),
        new("developer-tools", "Developer Tools", "Developer Tools", "DEV", ConsoleColor.DarkGray, DeveloperOnly: true),
        new("package-manager", "Package Manager", "Developer Tools", "PKG", ConsoleColor.DarkGray, DeveloperOnly: true),
        new("log-viewer", "Log Viewer", "Developer Tools", "LOG", ConsoleColor.DarkGray, DeveloperOnly: true),
        new("api-explorer", "API Explorer", "Developer Tools", "API", ConsoleColor.DarkGray, DeveloperOnly: true),
        new("hardware-test", "Hardware Test", "Developer Tools", "HW", ConsoleColor.DarkGray, DeveloperOnly: true),
        new("system-diagnostics", "System Diagnostics", "Developer Tools", "DIAG", ConsoleColor.DarkGray, DeveloperOnly: true),
    };

    public static IReadOnlyList<TileModel> StartTiles { get; } = new List<TileModel>
    {
        new("phone", "Phone", "☎", TileSize.Small, ConsoleColor.Blue),
        new("messages", "Messages", "💬", TileSize.Small, ConsoleColor.Green, Badge: 1),
        new("calendar", "Calendar", "8", TileSize.Medium, ConsoleColor.DarkCyan, LiveText: "Today: Bolun Phone 1.0"),
        new("mail", "Email", "✉", TileSize.Medium, ConsoleColor.Blue, Badge: 3),
        new("camera", "Camera", "📷", TileSize.Wide, ConsoleColor.DarkBlue, LiveText: "HDR • Night • QR • Documents"),
        new("bolun-ai", "Bolun AI", "AI", TileSize.Wide, ConsoleColor.Magenta, LiveText: "Assistant, OCR, search, translation"),
        new("weather", "Weather", "☀", TileSize.Wide, ConsoleColor.Blue, LiveText: "24° clear"),
        new("dima30-store", "Dima30 Store", "▣", TileSize.Medium, ConsoleColor.DarkGreen, LiveText: "Apps, updates, rollback"),
        new("music", "Music", "♪", TileSize.Medium, ConsoleColor.DarkBlue),
        new("maps", "Maps", "⌖", TileSize.Medium, ConsoleColor.DarkCyan),
        new("qr-scanner", "QR Scanner", "QR", TileSize.Small, ConsoleColor.DarkGreen),
        new("settings", "Settings", "⚙", TileSize.Small, ConsoleColor.DarkGray),
    };

    public static IReadOnlyList<NotificationModel> Notifications { get; } = new List<NotificationModel>
    {
        new("system", "Welcome", "Bolun Phone 1.0 by dima30 is ready", DateTimeOffset.Now),
        new("dima30-store", "Dima30 Store", "Safe removed apps stay installed; security removals are blocked with the official reason", DateTimeOffset.Now),
        new("bolun-pay", "Bolun Pay", "NFC devices show NFC + QR; non-NFC devices use QR code", DateTimeOffset.Now),
    };
}
